In [1]:
import numpy as np

## creating a numpy array

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#2d ndarray : matrics

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3d nd array: tensor

c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#aanother datatype:

a = np.array([1,2,3,4], dtype=float)
print(a)
print(type(a))
print(type(a[0]))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [11]:
#np.arange()

a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [12]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [14]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
b = np.zeros((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
a = np.random.random((2,3)).round(2)*100
print(a)

[[20.  7. 68.]
 [71.  7. 93.]]


In [32]:
#np.linspace

np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])