In [1]:
import numpy as np

## creating a numpy array

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#2d ndarray : matrics

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3d nd array: tensor

c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#aanother datatype:

a = np.array([1,2,3,4], dtype=float)
print(a)
print(type(a))
print(type(a[0]))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [11]:
#np.arange()

a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [12]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [14]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
b = np.zeros((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
a = np.random.random((2,3)).round(2)*100
print(a)

[[20.  7. 68.]
 [71.  7. 93.]]


In [32]:
#np.linspace

np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## numpy attributes:

In [38]:
#ndim:

a = np.arange(12).reshape(3,4)
print(a.ndim)

2


In [40]:
b = np.arange(8).reshape(2,2,2)
print(b)
print(b.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


In [41]:
b.shape

(2, 2, 2)

In [42]:
a.shape

(3, 4)

In [43]:
a.size

12

In [44]:
b.size

8

In [45]:
b.itemsize

8

In [46]:
a.itemsize

8

In [51]:
a.astype(np.bool)

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
a1 = np.arange(12).reshape(4,3)
print(a1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
a1*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [55]:
b1=np.arange(12).reshape(4,3)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [56]:
a1-b1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
a1+b1

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [58]:
a1>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [59]:
a1[a1>5]

array([ 6,  7,  8,  9, 10, 11])

## functions:

In [60]:
a = np.random.random((3,3))
a = np.round(a*100)
print(a)

[[54. 99. 72.]
 [28. 91.  2.]
 [86. 42. 59.]]


In [61]:
np.max(a)

np.float64(99.0)

In [62]:
np.min(a)

np.float64(2.0)

In [63]:
np.sum(a)

np.float64(533.0)

In [64]:
np.sum(a, axis=1)

array([225., 121., 187.])

In [66]:
np.sum(a, axis=0)

array([168., 232., 133.])

In [67]:
np.prod(a,axis=0)

array([130032., 378378.,   8496.])

In [68]:
np.mean(a, axis=1)

array([75.        , 40.33333333, 62.33333333])

In [69]:
np.mean(a)

np.float64(59.22222222222222)

In [72]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
np.log(a1)

C:\Users\shubh\AppData\Local\Temp\ipykernel_13120\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [75]:
print(a1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [81]:
a1[1:4,2]

array([ 5,  8, 11])

In [84]:
c = np.arange(27).reshape(3,3,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [88]:
c[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])