# NUMPY

#### Creating numpy arrays:

In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#2D and 3D numpy arrays:

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### dtype

In [12]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [13]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

#### np.arange()

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### with reshape

In [18]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### np.ones() and np.zeros()

In [23]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### np.random.random()

In [27]:
np.random.random((2,3))

array([[0.28621572, 0.64917429, 0.73787315],
       [0.23615324, 0.78330979, 0.9598577 ]])

#### np.linspace()

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
np.linspace(-4,9,3)

array([-4. ,  2.5,  9. ])

#### np.identity()

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [32]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

#### ndim

In [38]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


#### shape

In [40]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


#### size

In [41]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


#### itemsize

In [42]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


## Changing Datatype

In [46]:
#astye


a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [47]:
a3.dtype

dtype('int64')

## Array Operations

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [53]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Scalar Operations

In [52]:
#Arithemetic (+,-,*,/,%)

a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [54]:
#Relational

a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

#### Vector Operations

In [56]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array functions

In [57]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[14. 16. 56.]
 [18. 70. 58.]
 [90. 13. 85.]]


#### max/min/sum/prod

In [64]:
print(np.max(a1))

print(np.min(a1))

print(np.sum(a1))

print(np.prod(a1))

90.0
13.0
420.0
91167358464000.0


In [67]:
print(np.min(a1, axis=1))

[14. 18. 13.]


In [69]:
print(np.max(a1, axis=1))

[56. 70. 90.]


In [71]:
print(np.sum(a1, axis=0))

[122.  99. 199.]


In [73]:
print(np.prod(a1, axis=1))

[12544. 73080. 99450.]


#### mean/median/std/var

In [75]:
print(np.mean(a1))

46.666666666666664


In [76]:
print(np.median(a1))

56.0


In [78]:
print(np.std(a1))

29.944392908634274


In [80]:
print(np.var(a1))

896.6666666666666


In [82]:
print(np.mean(a1, axis=0))

[40.66666667 33.         66.33333333]


In [84]:
print(np.std(a1, axis=1))

[19.34482417 22.23110933 35.17890782]


#### triginometric functions

In [85]:
print(np.sin(a1))

[[ 0.99060736 -0.28790332 -0.521551  ]
 [-0.75098725  0.77389068  0.99287265]
 [ 0.89399666  0.42016704 -0.17607562]]


#### dot product

In [86]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [87]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [88]:
np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

#### log and exponents

In [90]:
print(np.log(a1))

[[2.63905733 2.77258872 4.02535169]
 [2.89037176 4.24849524 4.06044301]
 [4.49980967 2.56494936 4.44265126]]


In [92]:
print(np.log(a1, axis=0))

TypeError: log() got an unexpected keyword argument 'axis'

In [94]:
print(np.exp(a1))

[[1.20260428e+06 8.88611052e+06 2.09165950e+24]
 [6.56599691e+07 2.51543867e+30 1.54553894e+25]
 [1.22040329e+39 4.42413392e+05 8.22301271e+36]]


#### round/floor/ceil

## Indexing and Slicing

In [96]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [99]:
#Indexing:

#1d array:

print(a1[-1])

9


In [104]:
#2d array indexing:

print(a2[0][3])
print(a2[2][1])

print(a2[1,0])

3
9
4


In [108]:
#3d array:

print(a3[0,0,0])
print(a3[0,1,1])

0
3


In [110]:
#Slicing

#1d array:

print(a1[3:7])
print(a1[::-1])

[3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]


In [118]:
#2d array:

print(a2[0,:])
print(a2[:,2])

print(a2[1:,1:3])

print(a2[::2,::3])

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]


In [ ]:
#3d array:

a3 = np.arange(27).reshape(3,3,3)
print(a3)



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [121]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])