# NUMPY

#### Creating numpy arrays:

In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#2D and 3D numpy arrays:

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### dtype

In [12]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [13]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

#### np.arange()

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### with reshape

In [18]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])