# Numpy arrays vs python list

### speed:

In [1]:
#list:

import time

a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])

print(time.time() - start)

5.110876083374023


In [2]:
#numpy arrays:

import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c=a+b

print(time.time() - start)


0.36405277252197266


#### memory space:

In [3]:
#list:

a = [i for i in range(10000000)]

import sys

sys.getsizeof(a)

89095160

In [4]:
#numpy arrays:

a = np.arange(10000000)

sys.getsizeof(a)

80000112

In [5]:
#also in numpy arrays we can do dtype!!

a = np.arange(10000000, dtype=np.int32)
sys.getsizeof(a)

40000112

### conveneience

In [6]:
#list:

l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

c = []

for i in range(len(l1)):
    c.append(l1[i] + l2[i])

print(c)

[7, 9, 11, 13, 15]


In [8]:
#numpy arrays:

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

c = a1+a2

print(c)

[ 7  9 11 13 15]


## Advanced Indexing

In [ ]:
#normal indexing and slicing:
import numpy as np

a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
print(a[1,2])

5


In [14]:
print(a[1:3, 1:3])

[[4 5]
 [7 8]]


In [15]:
#fancy indexing:

a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [21]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

### Boolean Indexing

In [23]:
import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)
print(a)

[[35 91 58 13]
 [38 93 93 78]
 [72 69 16 75]
 [75 66  4 10]
 [49 20  9 50]
 [46 70 27 59]]
