# np.sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

[44 21 81 62 11 44 94 50 19 67 74 31  8 94 50]


In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[72 17 53 59]
 [62 60 77 34]
 [76 25 89 74]
 [38 80 68 96]
 [99  9 85 32]
 [36 69 18 66]]


In [4]:
print(np.sort(a))

[ 8 11 19 21 31 44 44 50 50 62 67 74 81 94 94]


In [5]:
print(np.sort(b))

[[17 53 59 72]
 [34 60 62 77]
 [25 74 76 89]
 [38 68 80 96]
 [ 9 32 85 99]
 [18 36 66 69]]


In [6]:
print(np.sort(b,axis=0))

[[36  9 18 32]
 [38 17 53 34]
 [62 25 68 59]
 [72 60 77 66]
 [76 69 85 74]
 [99 80 89 96]]


In [9]:
print(np.sort(a)[::-1])

[94 94 81 74 67 62 50 50 44 44 31 21 19 11  8]


# np.append

In [10]:
a = np.arange(5)
np.append(a,200)

array([  0,   1,   2,   3,   4, 200])

In [12]:
b = np.arange(1,13).reshape(4,3)

np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[ 1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  1.],
       [ 7.,  8.,  9.,  1.],
       [10., 11., 12.,  1.]])

# np.concatenate

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [16]:
e = np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6])
f = np.array([[1,2,3,1], [1,2,3,2]])

In [17]:
print(np.unique(e))

[1 2 3 4 5 6]


In [18]:
print(np.unique(f))

[1 2 3]


## np.where

In [20]:
a = np.random.randint(1,100,10)
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [21]:
#find all indices with value greater than 50
print(np.where(a>50))

(array([0, 2, 6, 7, 8, 9]),)


In [22]:
#replace all the vlues>50 with 0

np.where(a>50, 0, a)

array([ 0,  6,  0,  3, 28, 49,  0,  0,  0,  0], dtype=int32)

In [23]:
#replace all even numbers with 0:

np.where(a%2==0, 0, a)

array([ 0,  0, 79,  3,  0, 49,  0,  0,  0, 81], dtype=int32)

## np.argmax

In [25]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [27]:
print(np.argmax(a))

6


In [28]:
b = np.random.randint(1,100,9).reshape(3,3)
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [39]:
print(np.argmax(b, axis=0))

[2 0 2]


In [40]:
print(np.argmax(b, axis=1))

[1 1 2]


## np.argmin

In [41]:
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [42]:
print(np.argmin(b))

5


In [43]:
print(np.argmin(b, axis=0))

[0 2 1]


In [45]:
print(np.argmin(b, axis=1))

[0 2 1]


## np.cumsum

In [46]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [47]:
print(np.cumsum(a))

[ 64  70 149 152 180 229 317 405 489 570]


In [48]:
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [49]:
print(np.cumsum(b))

[ 38 106 148 192 251 252 309 356 436]


In [50]:
print(np.cumsum(b, axis=0))

[[ 38  68  42]
 [ 82 127  43]
 [139 174 123]]


In [52]:
print(np.cumsum(b, axis=1))

[[ 38 106 148]
 [ 44 103 104]
 [ 57 104 184]]


## np.cumprod

In [54]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [56]:
print(np.cumprod(a))

[              64              384            30336            91008
          2548224        124862976      10987941888     966938886144
   81222866436096 6579052181323776]


## np.percentile

In [57]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [59]:
print(np.percentile(a,100))

88.0


In [61]:
print(np.percentile(a,0))

3.0


In [63]:
print(np.percentile(a,50))

71.5


In [65]:
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [66]:
print(np.percentile(b,100))

80.0


## np.histogram

In [68]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [72]:
np.histogram(a, bins=[0,20,40,60,80,100])

(array([2, 1, 1, 2, 4]), array([  0,  20,  40,  60,  80, 100]))

## np.corrcoef

In [74]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [75]:
np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

In [76]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [79]:
items = [1,2,3,4,5,6,7,8,9,10]

print(a[np.isin(a,items)])

[6 3]


## np.flip

In [82]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [84]:
print(np.flip(a))

[81 84 88 88 49 28  3 79  6 64]


In [91]:
b = np.arange(1,13).reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [92]:
print(np.flip(b))

[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [93]:
print(np.flip(b, axis=0))

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [94]:
print(np.flip(b, axis=1))

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


## np.put

In [95]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [97]:
np.put(a,[0,1,2],[100,200,300])

In [98]:
print(a)

[100 200 300   4   5]


## np.delete

In [99]:
print(a)

[100 200 300   4   5]


In [100]:
np.delete(a,0)

array([200, 300,   4,   5])

In [103]:
b = np.array([1,2,3,4,5,6,7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


In [104]:
np.delete(b,[0,3,5,7])

array([2, 3, 5, 7, 9])

In [105]:
print(b)

[1 2 3 4 5 6 7 8 9]


## set functions

In [106]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [107]:
#np.unionn1d:

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [108]:
#np.intersect1d:

np.intersect1d(m,n)

array([3, 4, 5])

In [109]:
#np.setdiff1d:

np.setdiff1d(m,n)

array([1, 2])

In [110]:
#np.setxor1d:

np.setxor1d(m,n)

array([1, 2, 6, 7])

In [112]:
#np.in1d:

np.in1d(m,n)

C:\Users\shubh\AppData\Local\Temp\ipykernel_4892\756840455.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False,  True,  True,  True])

## np.clip

In [113]:
a = np.array([35,10,75,80,50,60,100])

In [114]:
np.clip(a, a_min=25, a_max=75)

array([35, 25, 75, 75, 50, 60, 75])