# np.sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

[44 21 81 62 11 44 94 50 19 67 74 31  8 94 50]


In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[72 17 53 59]
 [62 60 77 34]
 [76 25 89 74]
 [38 80 68 96]
 [99  9 85 32]
 [36 69 18 66]]


In [4]:
print(np.sort(a))

[ 8 11 19 21 31 44 44 50 50 62 67 74 81 94 94]


In [5]:
print(np.sort(b))

[[17 53 59 72]
 [34 60 62 77]
 [25 74 76 89]
 [38 68 80 96]
 [ 9 32 85 99]
 [18 36 66 69]]


In [6]:
print(np.sort(b,axis=0))

[[36  9 18 32]
 [38 17 53 34]
 [62 25 68 59]
 [72 60 77 66]
 [76 69 85 74]
 [99 80 89 96]]


In [9]:
print(np.sort(a)[::-1])

[94 94 81 74 67 62 50 50 44 44 31 21 19 11  8]


# np.append

In [10]:
a = np.arange(5)
np.append(a,200)

array([  0,   1,   2,   3,   4, 200])

In [12]:
b = np.arange(1,13).reshape(4,3)

np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[ 1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  1.],
       [ 7.,  8.,  9.,  1.],
       [10., 11., 12.,  1.]])

# np.concatenate

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [16]:
e = np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6])
f = np.array([[1,2,3,1], [1,2,3,2]])

In [17]:
print(np.unique(e))

[1 2 3 4 5 6]


In [18]:
print(np.unique(f))

[1 2 3]


## np.where

In [20]:
a = np.random.randint(1,100,10)
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [21]:
#find all indices with value greater than 50
print(np.where(a>50))

(array([0, 2, 6, 7, 8, 9]),)


In [22]:
#replace all the vlues>50 with 0

np.where(a>50, 0, a)

array([ 0,  6,  0,  3, 28, 49,  0,  0,  0,  0], dtype=int32)

In [23]:
#replace all even numbers with 0:

np.where(a%2==0, 0, a)

array([ 0,  0, 79,  3,  0, 49,  0,  0,  0, 81], dtype=int32)

## np.argmax

In [25]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [27]:
print(np.argmax(a))

6


In [28]:
b = np.random.randint(1,100,9).reshape(3,3)
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [39]:
print(np.argmax(b, axis=0))

[2 0 2]


In [40]:
print(np.argmax(b, axis=1))

[1 1 2]


## np.argmin

In [41]:
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [42]:
print(np.argmin(b))

5


In [43]:
print(np.argmin(b, axis=0))

[0 2 1]


In [45]:
print(np.argmin(b, axis=1))

[0 2 1]


## np.cumsum

In [46]:
print(a)

[64  6 79  3 28 49 88 88 84 81]


In [47]:
print(np.cumsum(a))

[ 64  70 149 152 180 229 317 405 489 570]


In [48]:
print(b)

[[38 68 42]
 [44 59  1]
 [57 47 80]]


In [49]:
print(np.cumsum(b))

[ 38 106 148 192 251 252 309 356 436]


In [50]:
print(np.cumsum(b, axis=0))

[[ 38  68  42]
 [ 82 127  43]
 [139 174 123]]


In [52]:
print(np.cumsum(b, axis=1))

[[ 38 106 148]
 [ 44 103 104]
 [ 57 104 184]]
