# NUMPY

#### Creating numpy arrays:

In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#2D and 3D numpy arrays:

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### dtype

In [12]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [13]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

#### np.arange()

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### with reshape

In [18]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### np.ones() and np.zeros()

In [23]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### np.random.random()

In [27]:
np.random.random((2,3))

array([[0.28621572, 0.64917429, 0.73787315],
       [0.23615324, 0.78330979, 0.9598577 ]])

#### np.linspace()

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
np.linspace(-4,9,3)

array([-4. ,  2.5,  9. ])

#### np.identity()

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [32]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

#### ndim

In [38]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


#### shape

In [40]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


#### size

In [41]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


#### itemsize

In [42]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


## Changing Datatype

In [46]:
#astye


a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [47]:
a3.dtype

dtype('int64')