# NUMPY

#### Creating numpy arrays:

In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#2D and 3D numpy arrays:

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
