# np.sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

[44 21 81 62 11 44 94 50 19 67 74 31  8 94 50]


In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[72 17 53 59]
 [62 60 77 34]
 [76 25 89 74]
 [38 80 68 96]
 [99  9 85 32]
 [36 69 18 66]]


In [4]:
print(np.sort(a))

[ 8 11 19 21 31 44 44 50 50 62 67 74 81 94 94]


In [5]:
print(np.sort(b))

[[17 53 59 72]
 [34 60 62 77]
 [25 74 76 89]
 [38 68 80 96]
 [ 9 32 85 99]
 [18 36 66 69]]


In [6]:
print(np.sort(b,axis=0))

[[36  9 18 32]
 [38 17 53 34]
 [62 25 68 59]
 [72 60 77 66]
 [76 69 85 74]
 [99 80 89 96]]


In [9]:
print(np.sort(a)[::-1])

[94 94 81 74 67 62 50 50 44 44 31 21 19 11  8]


# np.append

In [10]:
a = np.arange(5)
np.append(a,200)

array([  0,   1,   2,   3,   4, 200])

In [12]:
b = np.arange(1,13).reshape(4,3)

np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[ 1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  1.],
       [ 7.,  8.,  9.,  1.],
       [10., 11., 12.,  1.]])